import React from 'react';
import { Bell, Search, User, LogOut, QrCode, Download } from 'lucide-react';
import { AuthUser } from '../../types';

interface HeaderProps {
  user: AuthUser;
  onLogout: () => void;
}

export const Header: React.FC<HeaderProps> = ({ user, onLogout }) => {
  const generateQRCode = async () => {
    // This would integrate with the QR code generation functionality
    const QRCode = await import('qrcode');
    try {
      const qrCodeUrl = await QRCode.toDataURL(`SYSTEM_${user.id}_${Date.now()}`);
      
      // Create and download the QR code
      const link = document.createElement('a');
      link.download = `QR_System_${Date.now()}.png`;
      link.href = qrCodeUrl;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('Error generating QR code:', error);
    }
  };

  const exportReport = async () => {
    const { jsPDF } = await import('jspdf');
    
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(18);
    doc.text('LAPORAN SISTEM INVENTARIS', 20, 20);
    
    // Add date
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleDateString('id-ID')}`, 20, 30);
    doc.text(`Generated by: ${user.pegawaiName || user.username}`, 20, 40);
    
    // Add content
    doc.setFontSize(12);
    doc.text('RINGKASAN SISTEM:', 20, 55);
    doc.text('• Total Barang: 147', 25, 65);
    doc.text('• Sedang Dipinjam: 23', 25, 75);
    doc.text('• Barang Rusak: 3', 25, 85);
    doc.text('• Pengguna Aktif: 42', 25, 95);
    
    doc.save(`Laporan_Inventaris_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <header className="bg-cream-50 shadow-sm border-b border-primary-200 ml-64">
      <div className="px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="relative">
              <Search className="h-5 w-5 text-gray-400 absolute left-3 top-1/2 transform -translate-y-1/2" />
              <input
                type="text"
                placeholder="Cari barang, pengguna, atau catatan..."
                className="pl-10 pr-4 py-2 border border-primary-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent w-96 bg-white"
              />
            </div>
          </div>
          
          <div className="flex items-center space-x-4">
            {/* Quick Actions */}
            <button 
              onClick={generateQRCode}
              className="p-2 text-gray-400 hover:text-primary-600 transition-colors"
              title="Generate QR Code"
            >
              <QrCode className="h-6 w-6" />
            </button>
            
            <button 
              onClick={exportReport}
              className="p-2 text-gray-400 hover:text-primary-600 transition-colors"
              title="Export Report"
            >
              <Download className="h-6 w-6" />
            </button>
            
            <button className="relative p-2 text-gray-400 hover:text-primary-600 transition-colors">
              <Bell className="h-6 w-6" />
              <span className="absolute top-0 right-0 h-2 w-2 bg-danger-500 rounded-full"></span>
            </button>
            
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 bg-gradient-to-br from-primary-500 to-primary-600 rounded-full flex items-center justify-center shadow-sm">
                <span className="text-cream-50 font-semibold text-sm">
                  {(user.pegawaiName || user.username).split(' ').map(n => n[0]).join('').toUpperCase()}
                </span>
              </div>
              <div className="text-sm">
                <p className="font-medium text-gray-900">{user.pegawaiName || user.username}</p>
                <p className="text-primary-600">{user.role} - {user.unit}</p>
              </div>
              <button
                onClick={onLogout}
                className="p-2 text-gray-400 hover:text-danger-500 transition-colors"
                title="Logout"
              >
                <LogOut className="h-5 w-5" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
};