import React from 'react';
import { Bell, Search, LogOut, QrCode, Download } from 'lucide-react';
import { AuthUser } from '../../types';

interface HeaderProps {
  user: AuthUser;
  onLogout: () => void;
}

export const Header: React.FC<HeaderProps> = ({ user, onLogout }) => {
  const generateQRCode = async () => {
    // This would integrate with the QR code generation functionality
    const QRCode = await import('qrcode');
    try {
      const qrCodeUrl = await QRCode.toDataURL(`SYSTEM_${user.id}_${Date.now()}`);
      
      // Create and download the QR code
      const link = document.createElement('a');
      link.download = `QR_System_${Date.now()}.png`;
      link.href = qrCodeUrl;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('Error generating QR code:', error);
    }
  };

  const exportReport = async () => {
    const { jsPDF } = await import('jspdf');
    
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(18);
    doc.text('LAPORAN SISTEM INVENTARIS', 20, 20);
    
    // Add date
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleDateString('id-ID')}`, 20, 30);
    doc.text(`Generated by: ${user.pegawaiName || user.username}`, 20, 40);
    
    // Add content
    doc.setFontSize(12);
    doc.text('RINGKASAN SISTEM:', 20, 55);
    doc.text('• Total Barang: 147', 25, 65);
    doc.text('• Sedang Dipinjam: 23', 25, 75);
    doc.text('• Barang Rusak: 3', 25, 85);
    doc.text('• Pengguna Aktif: 42', 25, 95);
    
    doc.save(`Laporan_Inventaris_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <header className="bg-white shadow-sm border-b border-gray-200 ml-64 sticky top-0 z-40">
      <div className="px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="relative">
              <Search className="h-5 w-5 text-gray-400 absolute left-3 top-1/2 transform -translate-y-1/2" />
              <input
                type="text"
                placeholder="Cari barang, pengguna, atau catatan..."
                className="pl-10 pr-4 py-2.5 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent w-96 bg-gray-50 focus:bg-white transition-all"
              />
            </div>
          </div>
          
          <div className="flex items-center space-x-3">
            {/* Quick Actions */}
            <div className="flex items-center space-x-2 bg-gray-50 rounded-xl p-1">
              <button 
                onClick={generateQRCode}
                className="p-2.5 text-gray-600 hover:text-blue-600 hover:bg-white rounded-lg transition-all duration-200 group"
                title="Generate QR Code"
              >
                <QrCode className="h-5 w-5 group-hover:scale-110 transition-transform" />
              </button>
              
              <button 
                onClick={exportReport}
                className="p-2.5 text-gray-600 hover:text-green-600 hover:bg-white rounded-lg transition-all duration-200 group"
                title="Export Report"
              >
                <Download className="h-5 w-5 group-hover:scale-110 transition-transform" />
              </button>
            </div>
            
            <button className="relative p-2.5 text-gray-600 hover:text-blue-600 hover:bg-blue-50 rounded-xl transition-all duration-200">
              <Bell className="h-5 w-5" />
              <span className="absolute -top-1 -right-1 h-4 w-4 bg-red-500 rounded-full flex items-center justify-center">
                <span className="text-white text-xs font-bold">67</span>
              </span>
            </button>
            
            <div className="flex items-center space-x-3 bg-gradient-to-r from-gray-50 to-gray-100 rounded-xl p-2">
              <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-xl flex items-center justify-center shadow-lg">
                <span className="text-white font-semibold text-sm">
                  {(user.pegawaiName || user.username).split(' ').map(n => n[0]).join('').toUpperCase()}
                </span>
              </div>
              <div className="text-sm">
                <p className="font-semibold text-gray-900">{user.pegawaiName || user.username}</p>
                <p className="text-blue-600 font-medium">{user.role} • {user.unit}</p>
              </div>
              <button
                onClick={onLogout}
                className="p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all duration-200"
                title="Logout"
              >
                <LogOut className="h-5 w-5" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
};